### ISSUE TITLE
Repo does not exist?

### ISSUE THREAD

**Issue by remcoNL** [scateu/convert-srt-to-audacity-label#1]
Hi Scateu,

This looks like the perfect solution! But i'm not able to install it, I get this:
remco@remco-HP-Laptop ~ $ git clone scateu/convert-srt-to-audacity-label
fatal: repository 'scateu/convert-srt-to-audacity-label' does not exist

But you do exist, no? (-;

**Comment by scateu** [comment]
try

git clone https://github.com/scateu/convert-srt-to-audacity-label


Glad it helps.

**Comment by remcoNL** [comment]
Much better (-; Tx!
